services:
  - type: web
    name: arsemble-ai-fastapi
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api_server.py"
    region: singapore
    autoDeploy: true
